### ISSUE TITLE
Unable to change the font color using css for any modules except HiSB

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#2078]
The following code only works for HiSB module all other modules that contain strong's numbers are always displayed as red font color regardless of what the css file dictates.

Place the following code in the file style.css

```css
@font-face {
    font-family: 'Custom';
    src: url('./SILEOTSR.ttf') format('truetype');
}

.sword-KJV {
    font-family: 'Custom' !important;
}


.sword-KJV .strongs {
   color:    #9f6ead; 
   font-size: 1.5em;
   /*vertical-align: sub; */
   text-decoration: bold;
}


.night .sword-KJV .strongs {
   color: white; 
 font-size: 1.7em;
vertical-align: sub; 
}

```
